SELECT TOP (1000) [ID]
      ,[ProjectName]
      ,[Type]
      ,[Budget]
      ,[Total]
      ,[Actual]
      ,[Forecast]
      ,[Overbudget]
      ,[Remaining]
      ,[Category]
      ,[Progress]
  FROM [costcontrol].[dbo].[Projects]
